#include "MallocBinnedInsightsComponent.h"

#include "MallocBinnedInsightsStyle.h"

#define LOCTEXT_NAMESPACE "FMallocBinnedInsightsComponent"

namespace UE::Insights::MemoryProfiler::MallocBinned
{
	namespace ComponentPrivate
	{
		static const FName TabId = "MallocBinnedProfiler";
	}

	TSharedPtr<FMallocBinnedInsightsComponent> FMallocBinnedInsightsComponent::CreateInstance()
	{
		ensure(!Instance.IsValid());

		// Not initializing locally to avoid thread local storage code generated by the compiler
		if (!Instance)
		{
			Instance = MakeShared<FMallocBinnedInsightsComponent>();
		}

		return Instance;
	}

	void FMallocBinnedInsightsComponent::Initialize(IUnrealInsightsModule& Module)
	{
		bIsInitialized = true;

		// Register tick functions.
		OnTick = FTickerDelegate::CreateSP(this, &FMallocBinnedInsightsComponent::Tick);
		OnTickHandle = FTSTicker::GetCoreTicker().AddTicker(OnTick, 0.0f);
	}

	void FMallocBinnedInsightsComponent::Shutdown()
	{
		if (!bIsInitialized)
		{
			return;
		}
		bIsInitialized = false;

		Instance.Reset();
	}

	void FMallocBinnedInsightsComponent::RegisterMajorTabs(IUnrealInsightsModule& InsightsModule)
	{
		using namespace ComponentPrivate;

		const FInsightsMajorTabConfig& Config = InsightsModule.FindMajorTabConfig(TabId);

		if (Config.bIsAvailable)
		{
			// Register tab spawner for the malloc binned Insights.
			FTabSpawnerEntry& TabSpawnerEntry = FGlobalTabmanager::Get()->RegisterNomadTabSpawner(TabId,
				FOnSpawnTab::CreateRaw(this,  &FMallocBinnedInsightsComponent::SpawnTab), 
				FCanSpawnTab::CreateRaw(this, &FMallocBinnedInsightsComponent::CanSpawnTab))
				.SetDisplayName(Config.TabLabel.IsSet()   ? Config.TabLabel.GetValue()   : LOCTEXT("MallocBinnedInsights_TabTitle", "MallocBinned2 Insights"))
				.SetTooltipText(Config.TabTooltip.IsSet() ? Config.TabTooltip.GetValue() : LOCTEXT("MallocBinnedInsights_TooltipText", "Open the MallocBinned2 Insights tab"))
				.SetIcon(Config.TabTooltip.IsSet() ? Config.TabIcon.GetValue() : FSlateStyle::Get().CreateIcon("MallocBinnedInsights.Icon"));

			// Find the "Insights Tools" group, in the Menu dropdown
			const TSharedRef<FWorkspaceItem>* FoundWorkspace = FGlobalTabmanager::Get()->GetLocalWorkspaceMenuRoot()->GetChildItems().FindByPredicate(
				[](const TSharedRef<FWorkspaceItem>& WorkspaceItem)
				{
					return WorkspaceItem->GetDisplayName().ToString() == "Insights Tools";
				});

			if (FoundWorkspace)
			{
				TabSpawnerEntry.SetGroup(*FoundWorkspace);
			}
		}
	}

	void FMallocBinnedInsightsComponent::UnregisterMajorTabs()
	{
		FGlobalTabmanager::Get()->UnregisterNomadTabSpawner(ComponentPrivate::TabId);
	}

	bool FMallocBinnedInsightsComponent::Tick(float DeltaTime)
	{
		// It would be nice if we were able to extend the default UnrealInsightsLayout_v1.1 at FTraceInsightsModule::CreateSessionViewer
		// to allow third party component to start attached into the UnrealInsights window
		// if (FGlobalTabmanager::Get()->HasTabSpawner(ComponentPrivate::TabId))
		// {
		// 	TSharedPtr<SDockTab> Tab = FGlobalTabmanager::Get()->TryInvokeTab(ComponentPrivate::TabId);
		// }

		return false;
	}

	bool FMallocBinnedInsightsComponent::CanSpawnTab(const FSpawnTabArgs& Args) const
	{
		return true;
	}

	static SDockTab::FOnTabClosedCallback OnClosedCallback;
	TSharedRef<SDockTab> FMallocBinnedInsightsComponent::SpawnTab(const FSpawnTabArgs& Args)
	{
		const TSharedRef<SDockTab> DockTab = SNew(SDockTab)
			.Label(LOCTEXT("MallocBinnedInsights_TabTitle", "MallocBinned2 Insights"))
			.Clipping(EWidgetClipping::ClipToBounds)
			.TabRole(ETabRole::NomadTab);

		OnClosedCallback = SDockTab::FOnTabClosedCallback::CreateSPLambda(this,
			[](TSharedRef<SDockTab>)
			{
				UE_LOG(LogTemp, Warning, TEXT("Tab closed"))
			});
		DockTab->SetOnTabClosed(OnClosedCallback);

		return DockTab;
	}
}

#undef LOCTEXT_NAMESPACE
